env:
  - CABALVER=1.22 GHCVER=7.8.3 COVERAGE_SUITE=tests
  - CABALVER=1.22 GHCVER=7.8.3 COVERAGE_SUITE=psci-tests
  - CABALVER=1.22 GHCVER=7.6.3
  - CABALVER=1.22 GHCVER=7.10.1
  - CABALVER=1.22 GHCVER=7.10.1 STACKAGE=nightly
  - CABALVER=1.22 GHCVER=7.8.3 STACKAGE=lts
before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH="/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH"
install:
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - travis_retry cabal update
  - cabal install alex happy
  - cabal install --only-dependencies --enable-tests --enable-benchmarks
script:
  - ./travis-script.sh
after_script:
  - ./travis-after-script.sh
notifications:
  email: true
before_deploy: "./bundle/build.sh linux64"
deploy:
  provider: releases
  api_key: $RELEASE_KEY
  file:
    - bundle/linux64.tar.gz
    - bundle/linux64.sha
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
